packages:
  - apps/*
  - packages/*

# catalog:
#   "@vitest/browser": 3.1.4
#   "@vitest/coverage-v8": 3.1.4

# hoistPattern:
#   - ^(?!@vitest/spy|vitest|@vitest/spy|@vitest/spy/.*)$
#   - "!@types/react"

# nodeLinker: hoisted

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - cypress
  - esbuild
  - msw
