packages:
  - packages/*
  - apps/*
  - tools/*

# hoistPattern:
#   - ^(?!@vitest/spy|vitest|@vitest/spy|@vitest/spy/.*)$
#   - "!@types/react"

# nodeLinker: hoisted

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - cypress
  - esbuild
  - msw

catalogs:
  react-next:
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
    prettier: ^3.5.3
    react: ^19.0.0
    react-dom: ^19.0.0
    typescript: ^5.7.2
    vite: 6.3.5
    vitest: ^3.0.5
    eslint: "^9.32.0"
    "@tanstack/react-form": ^1.19.0
    "@tanstack/react-query": ^5.84.2
    graphql-request: ^7.2.0
    neverthrow: ^8.2.0
    zustand-mutative: ^1.3.0
    valibot: ^1.1.0
    zustand: ^5.0.7
    axios: ^1.11.0
    mutative: ^1.2.0
    "@vitest/browser": 3.1.4
    "@vitest/coverage-v8": 3.1.4
catalog:
  "@chromatic-com/storybook": ^4
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-tooltip": ^1.2.7
  "@storybook/addon-a11y": ^9.0.3
  "@storybook/addon-docs": ^9.0.3
  "@storybook/addon-onboarding": ^9.0.3
  "@storybook/addon-vitest": ^9.0.3
  "@storybook/react-vite": ^9.0.3
  "@tailwindcss/vite": ^4.1.7
  "@tanstack/react-router": ^1.120.11
  "@tanstack/react-router-devtools": ^1.120.11
  cypress: ^14.5.1
  lucide-react: ^0.511.0
  react-hot-toast: ^2.5.2
  tailwindcss: ^4.1.7
  tw-animate-css: ^1.3.0
