name: 'CI Pipline'

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install deps
              run: pnpm i

            - name: Run Lint
              run: pnpm lint
    unit_tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install deps
              run: pnpm i

            - name: Run Unit Tests
              run: pnpm test:unit

    integration_tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install deps
              run: pnpm i

            - name: Run Unit Tests
              run: pnpm test:unit

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm start
                  browser: chrome
