name: 'CI Pipline'

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install deps
              run: pnpm i

            - name: Run Lint
              run: pnpm lint

            - name: Run Type Checks
              run: pnpm type-check

    unit_tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install deps
              run: pnpm i

            - name: Run Unit Tests
              run: pnpm test:unit

    integration_tests:
        runs-on: ubuntu-latest
        needs: unit_tests

        steps:
            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install deps
              run: pnpm i

            - name: Cypress Component Testing
              run: pnpm test:integration:headless
