name: 'CI Pipline'

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Environment
              uses: ./.github/actions/setup-environment

            - name: Run Lint
              run: pnpm lint

            - name: Run Type Checks
              run: pnpm type-check

    unit_tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Environment
              uses: ./.github/actions/setup-environment

            - name: Run Unit Tests
              run: pnpm test:unit

    integration_tests:
        runs-on: ubuntu-latest
        needs: unit_tests

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              
            - name: Setup Environment
              uses: ./.github/actions/setup-environment

            - name: Install Cypress 📥
              run: pnpm i cypress

            - name: Run Cypress Component Tests
              uses: cypress-io/github-action@v6
              with:
                  component: true
                  browser: chrome
                  headed: false
