name: 'CI Pipeline'

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Environment
              uses: ./.github/actions/setup-environment

            - name: Run Lint
              run: pnpm lint:all

            - name: Run Type Checks
              run: pnpm type:check:all

    unit_tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Environment
              uses: ./.github/actions/setup-environment

            - name: Run Unit Tests
              run: pnpm test:all

    integration_tests:
        runs-on: ubuntu-latest
        needs: unit_tests

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              
            - name: Setup Environment
              uses: ./.github/actions/setup-environment

            - name: Go To App Folder
              run: cd apps/scratch-web

            - name: Install Cypress 📥
              run: pnpm i --filter scratch-web cypress

            - name: Run Cypress Component Tests
              uses: cypress-io/github-action@v6
              with:                  
                  component: true
                  browser: chrome
                  headed: false
