name: 'CI Pipline'

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: pnpm

            - name: Install deps
              run: pnpm i

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: |
                    node_modules 
                    ~/runner/.cache/Cypress
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Run Lint
              run: pnpm lint

            - name: Run Type Checks
              run: pnpm type-check

    unit_tests:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Restore node_modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Run Unit Tests
              run: pnpm test:unit

    integration_tests:
        runs-on: ubuntu-latest
        needs: unit_tests

        steps:
            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Restore node_modules
              uses: actions/cache@v3
              with:
                  path: |
                    node_modules 
                    ~/runner/.cache/Cypress
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Cypress Component Testing
              run: pnpm test:integration:headless
